### ISSUE TITLE
[BUG] Underground matches skybox color

### ISSUE THREAD

**Issue by SirFancyBacon** [117HD/RLHD#101]
**Describe the bug**
The ground under certain stairs/ladders/trapdoors around Runescape have the skybox instead of black.
![image](https://user-images.githubusercontent.com/11658143/198910819-0fe7269d-d3ef-4886-9abd-67ff8031df5c.png)

**Confirmed Locations**
East Ardougne basement stairs
GE Ladder to Keldagrim

**Expected behavior**
Black or some sort of dark color similar to vanilla
![image](https://user-images.githubusercontent.com/11658143/198910920-37671cf9-0bb0-4cca-87fb-45eb92f47ade.png)

**Environment (please complete the following information):**
 - OS: [Ubuntu 22.04 x64]
 - RLHD version: [1.2.4-Dev]
 - Runelie version: [1.9.3]

**Comment by aHooder** [comment]
Fixed by https://github.com/117HD/RLHD/commit/d340491a6cd4b59d29fe8fea874e02adc5a5ef9e.
