### ISSUE TITLE
Southernmost tunnel in barrows catacombs has the wrong skybox

### ISSUE THREAD

**Issue by ww3231** [117HD/RLHD#103]
**To Reproduce**
1. Go to 'barrows, find catacombs and navigate to the southern long tunnel'

**Expected behavior**
Skybox would match rest of the area

**Comment by Mark7625** [comment]
I am unable to reproduce this can you please send me your settings :)

**Comment by SirFancyBacon** [comment]
I am also unable to reproduce this; I am thinking this is either a skybox override or the winter theme issue.

With region filtering min PR#135 i believe that takes care of this; no?
