### ISSUE TITLE
[BUG] Iceberg Footprints have shadows. + texture & lighting improvements request.

### ISSUE THREAD

**Issue by PleaseRephraseNClarify** [117HD/RLHD#113]
**Locations**
Ice Berg & Areas reached during the Cold War quest

**Describe the bug**
Footprints have shadows under them
![image](https://user-images.githubusercontent.com/831317/200877023-c802b1d8-5380-4c42-a66b-fc529ee6c9b0.png)

**Expected behaviour:**
No shadows underneath footprints

**Iceberg Texture Feedback**
Top of ice looks like dirt instead of ice.

**Lack of lighting**
No indoor lighting 
![image](https://user-images.githubusercontent.com/831317/200877051-ce9907a9-7076-4247-9f44-72fe0070aad4.png)

**Steps to reproduce the behavior:**
Do quest: Cold War
Go to Iceberg

**Comment by aHooder** [comment]
The footprint issue can be fixed with `disableShadows` in `model_overrides.json`. For the ice, maybe those tiles could be set to `WaterType.ICE_FLAT`?
