### ISSUE TITLE
[Bug]Wrong texture on waterfall North of Prifddinas 

### ISSUE THREAD

**Issue by PleaseRephraseNClarify** [117HD/RLHD#114]
**Describe the bug**
Wrong texture on waterfall North of Prifddinas. Water looks like it's flowing upwards.

**To Reproduce**
Steps to reproduce the behaviour:
1. Complete Song of the Elves
2. Go to waterfall North of of Prifddinas 

**Expected behaviour**
Waterfall texture for waterfall

**Screenshots**
![image](https://user-images.githubusercontent.com/831317/200877188-0f0af6e2-a5e3-48ec-bb06-58fd6aba0c7d.png)

**Comment by Mark7625** [comment]
Fixed in #123
