### ISSUE TITLE
Wrong color with bridge tiles in Lumbridge

### ISSUE THREAD

**Issue by aHooder** [117HD/RLHD#127]
**Describe the bug**
There's a yellow streak with ground blending on the bridge in Lumbridge, possibly caused by inheriting color from the tiles underneath the bridge.

**To Reproduce**
Enable ground blending.

**Screenshots**
![image](https://user-images.githubusercontent.com/831317/202197824-8d95ee71-dbb7-4d26-8c6f-8322e834b65c.png)

**Comment by SirFancyBacon** [comment]
Looks like the same issue as #124

**Comment by aHooder** [comment]
> Looks like the same issue as #124

They're both related to bridge tiles, but ultimately have different causes I think.
