### ISSUE TITLE
Misplaced sand around OSRS

### ISSUE THREAD

**Issue by SirFancyBacon** [117HD/RLHD#171]
**Describe the bug**
Material 68 assigned to sand and it puts sand in areas where there is no business to be sand
![image](https://user-images.githubusercontent.com/11658143/222033691-ce917c37-8e79-44fe-89e5-cb9a174715bc.png)

This is mostly for my notes later to remember to fix this.

**To Reproduce**
1. Go to here:
![image](https://user-images.githubusercontent.com/11658143/222033798-c3a5c6b3-44dc-4558-a9b9-aa05628c7e22.png)
![image](https://user-images.githubusercontent.com/11658143/222033828-d0601f61-dfc2-438d-98d5-fd121c9ac448.png)

**Expected behavior**
Probably should be grass, but maybe dirt since i am sure this is used on a lot of beaches

**Comment by SirFancyBacon** [comment]
upon investigation the only solution i can find for this (without a lot of manual overides) is to allow for texture application based on tile hue.

**Comment by aHooder** [comment]
How's this coming along? :eyes:

**Comment by SirFancyBacon** [comment]
Closed with complex tiles is how 😎
