### ISSUE TITLE
Animations causing models to disappear after OSRS update on 18/4/23

### ISSUE THREAD

**Issue by mjsterling** [117HD/RLHD#187]
Certain animations are causing models to disappear while the animation is in progress:
- Teleports: default, fairy ring, puro puro
- Dragon battleaxe specs
- Premier Shield and Party emotes
- Chromatic dragons' dragonfire attack
- Hunllef attack animation

**Comment by Blunkie** [comment]
For some people 117 has disappeared not even appearing on the plugin hub.
