### ISSUE TITLE
Ignore textured areas of objects for UV remaping

### ISSUE THREAD

**Issue by SirFancyBacon** [117HD/RLHD#189]
**Is your feature request related to a problem? Please describe.**
The issue is pretextured objects, can you make it so the uvs in the areas of an object are left alone by your uv changes? Currently if I try to change the uv of an object with textures (trees) uvs it breaks the texture map of the original texture (leaves)

**Describe the solution you'd like**
apply the desired UvType only on surfaces textured by vanilla textures

**Additional context**
![image](https://user-images.githubusercontent.com/11658143/234977551-41cc1628-f6b1-4403-964c-3c337fdd881d.png)

**Comment by aHooder** [comment]
Fixed in https://github.com/117HD/RLHD/commit/3e00517e6fcbb585a220f198e5b3e0e9ee9a6f2e. Better late than never :slightly_smiling_face:
