### ISSUE TITLE
Unassigned overlay 80 causes graphical glitches

### ISSUE THREAD

**Issue by SirFancyBacon** [117HD/RLHD#190]
**Describe the bug**
Myths guild pathway overlay is unassigned

**To Reproduce**
1. Go to the path leading to the Myths Guild

**Expected behavior**
Assign overlay 80 to OVERLAY_DIRT_PATH

**Screenshots**
![image](https://user-images.githubusercontent.com/11658143/234982454-eba45f58-60a2-4fc5-a612-90c811d82538.png)

**Environment (please complete the following information):**
 - OS: Mint 21.1
 - RuneLite version: 1.9.16

**Comment by aHooder** [comment]
Does this mean that you're unable to apply the overlay change you want? Not sure I follow

**Comment by SirFancyBacon** [comment]
This is a reminder for me lol no worries.

But yes it needs to be changed. I decided to just change it and make "Sand fix" pr be "Sand and dirt material fixes"
