### ISSUE TITLE
Improper blending under Goblin Village

### ISSUE THREAD

**Issue by SirFancyBacon** [117HD/RLHD#191]
**Describe the bug**
Bad blending in Goblin Chefs basement in the Goblin Village north of Falador

**To Reproduce**
1. Speed run to the quest area

**Expected behavior**
Proper blending and material assignments

**Screenshots**
![image](https://user-images.githubusercontent.com/11658143/235010590-f9945521-594d-4138-8d5f-298e7d0f0fae.png)

**Comment by SirFancyBacon** [comment]
Notes: underlay 57 and 56 likely the checker pattern and are unassigned materials
Overlay 37 and underlay 118 are not assigned and are scorched marks

**Comment by aHooder** [comment]
I'm guessing this is the area prior to Recipe for Disaster, but it looks pretty broken there too:
![image](https://user-images.githubusercontent.com/831317/235010892-46647cbb-a404-4586-a9fb-36a5132482ad.png)
vs. vanilla:
![image](https://user-images.githubusercontent.com/831317/235010922-48a225f8-b7d4-4d02-ad7c-15372fb35ad5.png)

**Comment by SirFancyBacon** [comment]
Yeah just making notes about it above :)

**Comment by SirFancyBacon** [comment]
![image](https://user-images.githubusercontent.com/11658143/235013418-0205305a-8304-42b7-ac77-c818bafa1998.png)
I think i have a winner for this one

**Comment by SirFancyBacon** [comment]
Reason for those harsh edges:
![image](https://user-images.githubusercontent.com/11658143/235013708-99886ad1-ab42-42ea-b578-81b30160c7ac.png)

**Comment by SirFancyBacon** [comment]
![image](https://user-images.githubusercontent.com/11658143/235015124-3f6a3d68-5271-4c8b-840f-6e3e1dbeccaf.png)
Blending is still enabled but disabled right after the crater; Also adjusted the environment color

**Comment by aHooder** [comment]
Seems like it's still blending the sand tiles. Did you add an overlay/underlay for the sandy looking tiles too?
