### ISSUE TITLE
Poor performance on M1 Max since latest update

### ISSUE THREAD

**Issue by Nevotic** [117HD/RLHD#194]
Since the latest 117HD update where it changes the Saturation and Contrast from 'High, Very High' to a percentage input, the performance has tanked drastically on my MacBook Pro M1 Max. It seems something in the 117HD background is not working properly. When I turn the plugin on, I get 50FPS (not unlocked FPS). After moving through different areas it suddenly goes to 35 fps. Turning the plugin off and then back on fixes the issue, without moving the camera at all. And then it drops the fps again in another area.

I've also tried with another RL profile with just 117HD installed and the problem is also persistent there.

**Comment by Nevotic** [comment]
Thought it was fixed by upping the model size cache, but this only fixed the issue temporarily.

**Comment by aHooder** [comment]
This issue should hopefully be resolved in the latest plugin update. Restart RuneLite to give it a try 🙂
