### ISSUE TITLE
Missing/Incorrect texture on planted willow sapling

### ISSUE THREAD

**Issue by LieutenantKhaos** [117HD/RLHD#196]
I've noticed this for a while, the leaf texture on the planted willow sapling is blue. Any ideas?

![willow](https://github.com/117HD/RLHD/assets/38410667/990a6089-33f2-4444-902e-d967187c6bca)

**Comment by aHooder** [comment]
This seems pretty close to vanilla behaviour. I would guess it appears slightly blue due to smooth normals and HD's environmental lighting.

![image](https://github.com/117HD/RLHD/assets/831317/bf5af8b8-6581-478b-9865-6c350a665a40)
