### ISSUE TITLE
MacOS M1 10fps and visual glitches since latest update

### ISSUE THREAD

**Issue by Nevotic** [117HD/RLHD#197]
escribe the bug
117HD causes artifacts/visual glitches and insane fps drop to max 10 fps. Game is unplayable until 117HD is turned off.

To Reproduce

117HD on whilst on a MacBook Pro with the M1 Max chip, problem is instantly shown.
Expected behavior
Not show visual glitches and have a normal, stable fps instead of a max of 10 (unlock fps is turned off).

Screenshots
https://share.cleanshot.com/x7xGDTtQ

Environment (please complete the following information):

OS: MacOS 13.3.1(a)
RuneLite version: 2.6.3

**Comment by Tigeneer** [comment]
Seconding this issue. I am running Runelite on a M1 Pro 16" Mac. Vanilla settings, even reinstalling does not slove this issue. Graphics get all glitchy and framerate dips continuously until the RuneLite client crashes. Leaves graphical glitches on the screen when the plugin is turned off.


OS: MacOS Ventura 13.2.1
RuneLite version: 2.4.2

**Comment by PleaseWorkJustwanttoreportabug** [comment]
+1! Game is unplayable with 117HD and M1 Silicone at the moment. Turning the plugin off fixes the issue. When I turn 117hd on, the game instantly shows corrupted textures and then crashes within seconds.

**Comment by aHooder** [comment]
I'll be working to try to resolve this in the next few hours. Unfortunately I don't own a Mac, but I have been able to reproduce this issue just now in a virtual machine. Sorry to have caused this issue. OpenGL on Mac is quite unpredictable!

**Comment by aHooder** [comment]
This bug should be fixed now if you restart RuneLite or click Update in the plugin hub panel. Big thanks to Adam for figuring out how I accidentally broke it!
