### ISSUE TITLE
117HD Insta-Crashes Runelite on launch with Mac Silicon

### ISSUE THREAD

**Issue by PleaseWorkJustwanttoreportabug** [117HD/RLHD#198]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/RS117/RLHD/search?type=Issues)

**Describe the bug**
With 117hd enabled, OSRS crashes within 1-5 seconds consistently with runelite. Textures appear drastically stretched and corrupted. Game works perfectly with plugin turned off. This began happening on Saturday, May 13, 2023

**To Reproduce**
Log in with 117HD enabled.

**Expected behavior**
Game will drop in frame rate to single digits, textures will be corrupted or stretched dramatically. Game will then crash.

**Screenshots**

**Environment (please complete the following information):**
Mac OS M1 Max

**Comment by aHooder** [comment]
This should be fixed now if you restart RuneLite or update the plugin through the plugin hub panel.
