### ISSUE TITLE
Gaps Between Tiles

### ISSUE THREAD

**Issue by Blastburn94** [117HD/RLHD#203]
**Describe the bug**
Gaps appear between tiles, especially whenever the camera is moving. It is significantly more visible if using a skybox color that isn't black. Additionally, it shows up almost constantly in every frame if the camera is aligned with one of the cardinal directions and the camera is pointed straight down with the "Expand pitch limit" setting enabled in the Camera plugin. I have yet to find a location where this issue doesn't occur. I tested this bug with each setting toggled one-by-one in the 117 HD plugin settings - the gaps between tiles are always visible no matter what. This does not occur at all with the regular GPU plugin.

**To reproduce**
Simply turn on the 117 HD plugin with the default skybox color and optionally use the camera settings mentioned above to make it more visible, then move the camera around by moving your character.

**Expected behavior**
There shouldn't be any gaps in the terrain where the skybox bleeds through.

**Screenshots**
[https://i.imgur.com/c2bAQKU.jpeg](https://i.imgur.com/c2bAQKU.jpeg) Seams are visible by the fountains in this screenshot.
[https://www.youtube.com/watch?v=b0yzZRuS7O8](https://www.youtube.com/watch?v=b0yzZRuS7O8)

**Environment**
 - OS: Windows 11 Pro Version 22H2 64-Bit (OS Build 22621.1702)
 - RuneLite version: 1.10.0.6
 - Launcher version: 2.6.3
 - 117 HD plugin version: 1.2.8
 - GPU: AMD Radeon RX 7900 XTX

**Additional context**
This is the exact same issue that was reported by someone else before this project was forked: [https://github.com/RS117/RLHD/issues/232](https://github.com/RS117/RLHD/issues/232)

**Comment by aHooder** [comment]
This is a known bug. Thanks for the detailed bug report though. Maybe we'll try to fix this at some point.
