### ISSUE TITLE
Extreme lag on mouse click if framerate cannot be met

### ISSUE THREAD

**Issue by MithicSpirit** [117HD/RLHD#210]
**Describe the bug**
If the maximum framerate (monitor's framerate if vsync, FPS target if FPS is unlocked, or the 50 fps default) cannot be met then mouse clicks are extremely delayed (up to 2 or 3 seconds, depending on exact configuration) and the client lags or hangs in the interim.

**To Reproduce**
Steps to reproduce the behavior (on my system; almost certainly hardware/performance-dependent):
1. Open 117 HD settings
2. Disable plugin
3. Increase settings to substantially reduce framerate while remaining reasonable: 20 to 30 fps works (default settings are sufficient on my hardware)
4. Raise maximum framerate (as described above) to be higher than what can be rendered
5. Enable plugin
6. Notice that the graphical performance is still decent (animations play at a decent FPS, though not reaching the maximum)*
7. Click on anything (including RuneLite UI; doesn't have to be in the game itself)
8. Observe lag/hang*

*Using Tile Indicator's Hovered Tile option can easily demonstrate this since the hovered tile tracks the mouse easily before clicking, but stays still while lagging/hanging.

**Expected behavior**
Mouse clicks shouldn't significantly affect client performance.

**Environment (please complete the following information):**
 - OS: Arch Linux
 - RuneLite version: 1.10.1
 - Launcher version: 2.6.4
 - 117 HD version: 1.2.8

**Comment by aHooder** [comment]
I can't reproduce this (at least not at ~30 FPS), leading me to believe it would either only happen if the frame rate was horribly low, or if another plugin was interfering with clicks. Please let me know if you're still able to reproduce this, and if so whether it still happens if you disable all other hub plugins and restart RuneLite to make sure they've been properly cleaned up.

**Comment by MithicSpirit** [comment]
Does seem to have been fixed now, as I can't reproduce it either (even when lagging out my system severely). Thanks!
