### ISSUE TITLE
HD client suddenly stopped working on MAC

### ISSUE THREAD

**Issue by TaylorKrill** [117HD/RLHD#221]
I can log on my OSRS account but with the HD client when I click play now it automatically closes the programme off. I cannot understand because it worked perfectly fine just yesterday.

**Comment by aHooder** [comment]
@TaylorKrill can you please join our Discord server so we can look into this? https://discord.gg/U4p6ChjgSE Feel free to ping `@Hooder` in the #mac-support channel

**Comment by heidincloset** [comment]
I've been experiencing the same issue with runelite on Mac today. Mine was working fine last night as well. I've uninstalled all plugins and the only one that causing crashing on 'click now to play' is 117 HD

**Comment by aHooder** [comment]
@heidincloset Please hop into our Discord server so we can collect some more info on this. We are working on getting it resolved :slightly_smiling_face:

**Comment by HelluvaRoman** [comment]
Can confirm, I am having the same issue with the 117 HD plugin. GPU plugin also has the same issue for me. HD plugin worked fine last night for me as well.

**Comment by aHooder** [comment]
This should be fixed with the latest plugin update. Either restart RuneLite or click the Update button in the plugin hub panel to update.
