### ISSUE TITLE
Hollow Trees in Morytania rendered through walls

### ISSUE THREAD

**Issue by 67protons** [117HD/RLHD#224]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/RS117/RLHD/search?type=Issues)

**Describe the bug**
At a low camera angle, I noticed Hollow Trees out in the distance were poking through the Ectofuntus walls

**To Reproduce**
1. Go to 'Ectofuntus'
2. Run to the north exit on the steps
3. Zoom in and lower camera

**Expected behavior**
Hollow Trees should be hidden behind Ectofuntus walls

**Screenshots**
![image](https://github.com/117HD/RLHD/assets/9568187/c2da5f1b-c701-49ce-8747-bbb9472cb7c7)

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 2.6.4
 - Launcher version: 2.1.6

**Comment by aHooder** [comment]
This is a vanilla bug, so it's arguably working correctly, but I agree it's ugly. It happens with the palm trees on Karamja as well for instance. It has to do with how our renderer (like vanilla) is based entirely around draw order, and the game engine happens to draw these tree tops after those walls. It might get fixed either by Jagex or by us at some point if we change some fundamental part of our renderer (or maybe add a hacky way to change draw order), but it'll likely continue to be an issue for at least a good while. Doesn't hurt to leave this issue open though.

**Comment by 67protons** [comment]
Oh I didn't realize it was vanilla. I saw it fix itself when I disabled 117HD and repro after re-enabling the plug-in so I thought  maybe it was 117HD-specific. I did see the Karamja palm trees bug on the old repo, but I assumed it might be different issues? Or perhaps there's some extra context I could be missing.

**Comment by Mark7625** [comment]
I was able to replicate this on vanilla So i will be closing the issue I hope jagex fixes this issue soon.
