### ISSUE TITLE
Leviathan Boulders disappearing with plugin turned on

### ISSUE THREAD

**Issue by amerheb** [117HD/RLHD#225]
**Describe the bug**
Boulders are disappearing, when they should not be:
https://streamable.com/1gfsve

**To Reproduce**
Fight the Leviathan with the 117 HD plugin enabled, with these settings:
![image](https://github.com/117HD/RLHD/assets/43042982/96ed2ef3-73fd-4827-942d-ff49381c3bcb)
![image](https://github.com/117HD/RLHD/assets/43042982/afed56a5-cfda-476b-b1df-901300dbfb90)

**Expected behavior**
Certain boulders should NOT disappear

**Screenshots**
See above

**Environment (please complete the following information):**
 - OS: Windows 11 Pro
 - RuneLite version: 1.10.9.1
 - Launcher version: 2.1.7

**Comment by aHooder** [comment]
I think this must've been a different plugin hiding these, as I've never been able to reproduce it. Feel free to reopen it if you're still seeing this after disabling all other hub plugins and restarting RuneLite to make sure they've been cleaned up.
