### ISSUE TITLE
fletching animation bug with black crystal legs and ferocious gloves on female avatar

### ISSUE THREAD

**Issue by Likkix** [117HD/RLHD#229]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/RS117/RLHD/search?type=Issues)

**Describe the bug**
when fletching magic longbows as a female avatar while wearing black crystal legs and ferocious, a strange shape bridges the gap between the crystal legs and the ferocious gloves on the avatar's left hand. On closer inspection, this bridge is present when avatar is in default stance. This bug extends to use of the blowpipe and presumably any other left-handed animation.  
**To Reproduce**
1. Go to anywhere wearing aforementioned gear as female npc
2. Observe shape between avatar's left hip and left hand. Do activity if necessary.

**Expected behavior**
A small black shape continuously bridges the gap between black crystal legs and ferocious gloves 
**Screenshots**
https://snipboard.io/XvNQgs.jpg
https://snipboard.io/CIXeGl.jpg
https://snipboard.io/QP8hfv.jpg

**Environment (please complete the following information):**
 - OS: Windows 11 Home
 - RuneLite version: unsure
 - Launcher version: Unsure

**Additional context**

**Comment by aHooder** [comment]
Does this only happen with 117 HD turned on?

**Comment by Likkix** [comment]
> Does this only happen with 117 HD turned on?

Yes, the bug did not appear when 117HD was turned off.

**Comment by aHooder** [comment]
I'm seeing the same bug without 117 HD, so I think this is a Jagex bug. Thanks for reporting it just in case though :slightly_smiling_face: 
![image](https://github.com/117HD/RLHD/assets/831317/b522c1b9-08c7-4ce0-b11c-e7268d423416)
