### ISSUE TITLE
Colors on POH Zen garden broke

### ISSUE THREAD

**Issue by corinnebunch** [117HD/RLHD#230]
![ZenGardenUgly](https://github.com/117HD/RLHD/assets/5633761/79e065df-2a71-4c80-84b6-b62f9f219d7a)
The Zen style for POH superior garden now shows ugly green/grey colors instead of the original bluegreen/cream. Original colors return when turning the 117 HD plugin off.

**Comment by aHooder** [comment]
Thanks for reporting this, but this has actually just been patched. If you restart RuneLite or click on Update in the plugin hub sidebar, it should be fixed :slightly_smiling_face:

**Comment by corinnebunch** [comment]
> Thanks for reporting this, but this has actually just been patched. If you restart RuneLite or click on Update in the plugin hub sidebar, it should be fixed 🙂

yayyy thanks! <3
