### ISSUE TITLE
117 HD Plug-in turning off when I teleport

### ISSUE THREAD

**Issue by Blodhevn** [117HD/RLHD#231]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/RS117/RLHD/search?type=Issues)

**Describe the bug**
When I teleport or when I hop worlds, the 117 HD plug-in turns itself off automatically. It's consistent and happens nearly every time. It just started doing this today as of 09/10/23.

Also, I'm suddenly having chunk loading issues.

**To Reproduce**
Teleport to anywhere
Hop to any world

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.10.12.1
 - Launcher version: 2.4.2

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
[client.log](https://github.com/117HD/RLHD/files/12570661/client.log)

https://github.com/117HD/RLHD/assets/144629206/6e185d46-370a-4f48-82c6-e70c797a1a98

**Comment by aHooder** [comment]
It looks like you are running out of memory due to using the 32-bit version of RuneLite. The 64-bit version should fix this. https://runelite.net/

**Comment by Blodhevn** [comment]
> 

This appears to have fixed my issues. Tested multiple times and can't get it to duplicate the previous issues. Thank you!

**Comment by aHooder** [comment]
Glad to hear :slightly_smiling_face:
