### ISSUE TITLE
Flat shading on some objects that should have smooth shading

### ISSUE THREAD

**Issue by peiwand1** [117HD/RLHD#235]
**Describe the bug**
For a little while now the shading on some, but not all objects has become flat (see screenshot). I believe it started at/a few days after [this runelite GPU plugin update](https://runelite.net/blog/show/2023-09-09-1.10.12-Release). This seems to mostly happen to trees, bushes and rocks, but may have happened to other objects as well. Some trees, such as evergreens, do not get this flat shading.

No changes were made to the plugin settings before this happened, though I did attempt to change the settings to fix it. This did not work, resetting the plugin settings similarly did not change this behavior.

**To Reproduce**
1. Simply having the plugin on causes this to occur
2. The plugin settings do not seem to affect this bug

**Expected behavior**
The affected objects should have smooth shading like in the top part of the included screenshot, rather than the ugly flat shading.

**Screenshots**
Top part of the screenshot shows the area west of Catherby bank with the normal GPU plugin, below that is the same area once 117HD is enabled. As you can see, the trees suddenly look way blockier due to the change in shading.

![shading](https://github.com/117HD/RLHD/assets/49898715/c1798e6c-2baf-4b09-8f43-c69e65d74ff2)

**Environment:**
 - OS: Windows 10
 - RuneLite version: 1.10.13
 - Launcher version: 2.6.8

**Comment by aHooder** [comment]
Thanks for reporting this. Helps us track down an issue that seemed unrelated :slightly_smiling_face:

**Comment by peiwand1** [comment]
I actually noticed something new today that I caught on video, the shading seems to change when new areas are loaded in. I assume that means it's probably in some way related to the new extended map loading feature.


https://github.com/117HD/RLHD/assets/49898715/3793efef-8c78-42ab-b89b-e712d8167f97

**Comment by SirFancyBacon** [comment]
> I actually noticed something new today that I caught on video, the shading seems to change when new areas are loaded in. I assume that means it's probably in some way related to the new extended map loading feature.

Does it pop back in if you load the previous area? Or does it stay off all the time?

**Comment by peiwand1** [comment]
After doing some more experimentation (and using a plugin to show chunk borders) I have noticed the following:

- The bug is not present when teleporting to an area
- The bug can seemingly happen in any area of the game
- Walking far enough that the game needs to load the next chunk causes the bug to appear
- The bug seems to apply per game chunk, the 1st image below shows 2 chunks next to each other with one bugged.
- Walking back the other way seems to fix the bug sometimes, but only in that chunk.
- Sometimes when walking even further, so another load trigger is hit, the bugged trees in an area also get fixed.
- Sometimes only specific object types get bugged within a chunk (like only oak trees for example, 2nd image shows this happening with some rocks).
- Within a given chunk, when 1 object of a type is bugged, all other objects of that type will also be bugged. So never SOME oak trees in the chunk, it's all or nothing.
- The bug is not specific to trees, but they are abuntant and easy to notice so they make for good testing. I have seen things like rocks, haystacks and bushes also display this bug.

![image](https://github.com/117HD/RLHD/assets/49898715/4dc47957-b478-4a45-a599-54489000af13)

![image](https://github.com/117HD/RLHD/assets/49898715/daabc8a5-40ee-480a-89bc-94c1a74769f0)

**Comment by aHooder** [comment]
This will be fixed internally in RuneLite for the next release. Thanks for the detailed bug report! I'll keep this open until the fix is out.
