### ISSUE TITLE
Does not work on Ubuntu - Shoes all blue scren

### ISSUE THREAD

**Issue by darthsiderius** [117HD/RLHD#266]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/RS117/RLHD/search?type=Issues)

**Describe the bug**
When using the 117 HD plugin on a new installation of rune lite on ubuntu, it shows blue screen instead of HD environment

**To Reproduce**
1. Install RuneLite on ubuntu
2. Install 117 HD plugin and enable
3. observe blue environment

**Expected behavior**
Show HD version 

**Screenshots**

![Screenshot from 2023-11-01 12-38-44](https://github.com/117HD/RLHD/assets/26830466/b0d4f503-b061-405b-9edf-936ff8cc4d4f)

**Environment (please complete the following information):**
 - OS:  Ubuntu 22.04.3 LTS, X11 windowing
 - AMD® Radeon rx 5600 xt GPU, AMD 7 3700X CPU
 - RuneLite version: most recent

**Comment by aHooder** [comment]
I'm not sure how I missed this until now, sorry. This is an issue with Mesa version 23.0. If you install Mesa 23.1 or up, it should be fixed.
