### ISSUE TITLE
Lighting for trailblazer fire effects/animations

### ISSUE THREAD

**Issue by korvl38** [117HD/RLHD#279]
As the title suggests. Would be sick to see. thanks

**Comment by SirFancyBacon** [comment]
This is actually already in master and should be in the emxt release 😎

**Comment by aHooder** [comment]
Forestry campfires will have lights, but we've not added lights for trailblazer animations, so I'll leave this issue open

**Comment by korvl38** [comment]
@aHooder @SirFancyBacon thank you i cant wait to see 😎
