### ISSUE TITLE
Werewolves shaking

### ISSUE THREAD

**Issue by Z-Kaz** [117HD/RLHD#28]
Werewolves, at least in the GWD, seem to shake when standing still.
![2022-08-08_22-15-54](https://user-images.githubusercontent.com/49293460/183556411-00b1dd60-58c2-468c-94b4-535d18df7c0e.png)
l

**Comment by Mark7625** [comment]
This is a Jagex issue or a animation smoothing bug, If animation smoothing is turned on turn it off

**Comment by Z-Kaz** [comment]
definitely animation smoothing. Thanks for the fix

**Comment by Mark7625** [comment]
Report it in the runelite chat please :)

**Comment by Z-Kaz** [comment]
Will do
