### ISSUE TITLE
Add "Hide unrelated maps" option from GPU plugin

### ISSUE THREAD

**Issue by ShaunDreclin** [117HD/RLHD#289]
The built-in GPU plugin has an option to hide unrelated maps (like seeing neighbouring runecrafting altars when you're not in them), could that feature be ported to this plugin?

**Comment by vhnunes** [comment]
Just made a casual test porting the hide unrelated maps from GPU to 117hd, seems to work.
![image](https://github.com/117HD/RLHD/assets/37745505/17558bed-a44f-4b4f-85e5-758cdca1e170)

BUT... Gpu plugin do not support skybox and this feature with hiding unrelated maps results in some visual issues 🤔
![image](https://github.com/117HD/RLHD/assets/37745505/6e79aad4-c825-40a3-aeaf-2c9ef9a245cc)

**Comment by vhnunes** [comment]
My lazy implementation diff [is here](https://github.com/117HD/RLHD/compare/master...vhnunes:RLHD:feature/hide-unreleated-maps)

**Comment by Jin-Jiyunsun** [comment]
What do you mean by GPU doesnt support skybox?

![image](https://github.com/117HD/RLHD/assets/37377657/9ef8c8ed-211e-42d1-8c44-ebc09fc57e6b)

**Comment by vhnunes** [comment]
Hmm, didn`t remember this feature from gpu. If they can make it work, it`s just a question to find out how

**Comment by Mark7625** [comment]
Hey I have already converted Runelite's to the one I made a while ago with more areas, I'm yet to pr it as it needs testing but i will work on it next

**Comment by ShaunDreclin** [comment]
Awesome, thank you!
