### ISSUE TITLE
Items very dark - shading broken?

### ISSUE THREAD

**Issue by Zels123** [117HD/RLHD#293]
This is a visual only bug but with in the last 2 days items have be come very dark I even reset the plugin settings but the issue still persists. I have tried increasing the brightness and everything else I can think of but no changes.

Example:
![image](https://github.com/117HD/RLHD/assets/6403112/cf486b24-73b0-451e-8bd7-0c495f7297c5)

**Comment by aHooder** [comment]
Do you mean the items in your inventory?

**Comment by Zels123** [comment]
Yeah compared to the shade it was for the last like 2 years they are very dark.

**Comment by aHooder** [comment]
The inventory brightness can be changed with the in-game brightness slider. Look for the slider next to a sun icon here: 
![image](https://github.com/117HD/RLHD/assets/831317/c664cfb6-37c2-4e4d-9580-6dc1e398bc0c)

**Comment by Zels123** [comment]
Oh Jesus I must have accidently messed with that setting, thank you!

**Comment by aHooder** [comment]
No problem :+1:
