### ISSUE TITLE
Tropical places have snow when they shouldn't

### ISSUE THREAD

**Issue by Jin-Jiyunsun** [117HD/RLHD#331]
Tropical areas currently have snow in winter, this issue is to track which areas are tropical and should not have snow.

Karamja and Brimhaven/Musa Point of course:
![image](https://github.com/117HD/RLHD/assets/37377657/dd601a3c-00fc-46e9-86fa-7ef607fee37e)

Ape Atoll:
![image](https://github.com/117HD/RLHD/assets/37377657/c4f5365b-bb0d-4279-b785-f500a67b6cc9)

Feldip Hills in the red box is covered in tall jungle palms and vines:
![image](https://github.com/117HD/RLHD/assets/37377657/3eba66fb-a1e6-424c-a966-ad52a2df6cac)

Mos Le'Harmless(and Harmony Island?):
![image](https://github.com/117HD/RLHD/assets/37377657/63d68be8-7855-4471-9370-151915c7e409)

**Comment by SirFancyBacon** [comment]
@Jin-Jiyunsun i believe you can mark this as closed.
