### ISSUE TITLE
Waterbirth Island Dungeon water regression

### ISSUE THREAD

**Issue by ipkpjersi** [117HD/RLHD#343]
**Describe the bug**
Water appearance has regressed in the Waterbirth Island Dungeon. 

**To Reproduce**
1. Download the repo and checkout master branch. 
2. Run HdPluginTest.
3. Go into the Waterbirth Island Dungeon.
4. Look at the water, it's the wrong color and missing the water effects.

**Expected behavior**
I expect the water to have the correct color and to have the water effects.

**Screenshots**
Here is what it looked like when it was working properly: 
![](https://i.imgur.com/n5uCjMk.png)

Here is what it looked like when it was immediately broken: 
![](https://i.imgur.com/mocRcuA.png)

Here is what it looks like now on master branch, it's like a combination of the two screenshots: 
![](https://i.imgur.com/inU7mxn.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - RuneLite version: 1.10-21-SNAPSHOT

**Additional context**
This is a regression caused by something in the Autumn theme commit: https://github.com/117HD/RLHD/commit/95652e2018cfab72b90afef066bd4ed7d043c4ae

The last commit with water that was looking correct  is the one before Autumn theme, this was region box based AABBs: https://github.com/117HD/RLHD/commit/7916b60a7342939bd411e06293c66978bcbb1174

Here is a video of the current water on master branch: https://streamable.com/ot49vq

Here is a video of what the water used to look like and should look like: https://streamable.com/x0slf8

**Comment by SirFancyBacon** [comment]
First off stellar bug report!

the current water in master is the intended behavior; before all water was being applied globally with overrides in some places; this caused outdoor water to appear indoor; the stagnated "Swamp water" is what was decided on.

**Comment by ipkpjersi** [comment]
Oh, I see, I wasn't aware this was decided on.
