### ISSUE TITLE
World is rendered as one solid color

### ISSUE THREAD

**Issue by Lambdara** [117HD/RLHD#354]
**Describe the bug**
When enabling 117HD, the world is suddenly drawn as one solid color.

**To Reproduce**
Install and enable 117HD

**Expected behavior**
The world to be drawn normally.

**Screenshots**
![Screenshot from 2024-02-21 10-00-59](https://github.com/117HD/RLHD/assets/9699777/10808188-979a-42c6-8bc4-d6fffc4d2524)

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04.4 LTS
 - RuneLite version: 1.10.22
 - Launcher version: 2.6.13

**Additional context**
Starting Runelite from a terminal gives some very interesting output when enabling 117HD:

```
/usr/share/libdrm/amdgpu.ids: No such file or directory
2024-02-21 09:54:41 CET [Client] INFO  rs117.hd.HdPlugin - Using device: NAVI23 (navi23, LLVM 15.0.7, DRM 3.46, 5.18.8-051808-generic)
2024-02-21 09:54:41 CET [Client] INFO  rs117.hd.HdPlugin - Using driver: 4.6 (Compatibility Profile) Mesa 23.0.4-0ubuntu1~22.04.1
2024-02-21 09:54:41 CET [Client] INFO  rs117.hd.HdPlugin - Client is 64-bit
2024-02-21 09:54:41 CET [Client] INFO  rs117.hd.HdPlugin - Low memory mode: false
ac_rtld error(1): too much LDS (used = 60732, max = 32768)
LLVM failed to upload shader
EE ../src/gallium/drivers/radeonsi/si_state_shaders.cpp:2557 si_build_shader_variant - Failed to build shader variant (type=3)
ac_rtld error(1): too much LDS (used = 60732, max = 32768)
LLVM failed to upload shader
EE ../src/gallium/drivers/radeonsi/si_state_shaders.cpp:2557 si_build_shader_variant - Failed to build shader variant (type=3)
```

This is interesting for a few reasons:
- `/usr/share/libdrm/amdgpu.ids` actually does exist, despite what the client is reporting.
- Mesa 23.0.4 is mentioned as the driver being used, but `glxinfo` shows me that the version of mesa installed on my system is 24.0.1.

Perhaps these things have to do with snap, I'm not sure.

**Comment by aHooder** [comment]
This is a mesa bug with specifically version 23.0. If you're using the flatpak version of RuneLite, try running `flatpak update`. Alternatively, you could try the AppImage from RuneLite's website instead, as the issue should be resolved in Mesa 24.

**Comment by Lambdara** [comment]
Thanks for the quick response, I'll give them a try and get back to you asap.

**Comment by Lambdara** [comment]
Allright, I uninstalled the RuneLite snap and installed the AppImage, and that seems to have fixed the issue. Thanks for the help!
