### ISSUE TITLE
Varlamore's ground textures are mostly wrong

### ISSUE THREAD

**Issue by saukko28** [117HD/RLHD#375]
**Describe the bug:**
Varlamore's ground textures are wrong in most of the places (see attached picture).
![Varlamore_Bugged](https://github.com/117HD/RLHD/assets/8791488/a3b5c4a7-3b41-4c24-814e-110a7f2d5978)

**Expected behavior:**
When turning 117 HD plugin off, you can clearly see what the ground textures should look like (see the attached picture).
![Varlamore_Expected](https://github.com/117HD/RLHD/assets/8791488/9e86ee59-35cc-4275-b59e-1b6fcbe13991)

**Environment:**
 - OS: Windows 10
 - RuneLite version: 1.10.25
 - Launcher version: 2.6.10

**Comment by Mark7625** [comment]
Already known and a fix should be out soon thanks a lot :)

**Comment by aHooder** [comment]
We're working on a fix indeed. For now you can disable Ground Textures to get the area looking mostly correct.

**Comment by saukko28** [comment]
Well that was fast! I can deal with the white ground textures just fine for the time being. 😌

Thank you in advance!

**Comment by saukko28** [comment]
Awesome! I updated the plugin and even the trees outside the city are fixed. Excellent job!
