### ISSUE TITLE
Perilous moons floor doesn't appear

### ISSUE THREAD

**Issue by Hibbs6** [117HD/RLHD#386]
**Describe the bug**
In the new dungeon, Perilous Moons, there are tiles showing the different phases of the moon on the floor underneath each boss. While 117HD is active, those tiles don't appear. The main active tile still does appear, so the content is playable, but at the moment, we're missing out on a lot of the theming and ability to predict exactly where the next circle is going to be.

**To Reproduce**
Activate 117 HD

Fight a boss in Perilous Moons and look at the floor, can toggle 117 HD on and off to compare.

**Expected behavior**
The floor tiles show up as per vanilla.

**Screenshots**
I don't have a screenshot right now, but if needed, I can grab one later.

**Comment by aHooder** [comment]
Thanks for the report :+1: This is something that could've probably gone unnoticed at least by me.

**Comment by aHooder** [comment]
I've looked into this now, and I don't see what you mean exactly, sorry. I only see the main glow on the phase of the moon you're supposed to stand on currently. Is it possible you have the Low Detail plugin enabled? That hides the moon phase symbols.

**Comment by Hibbs6** [comment]
I'm so sorry! It was in fact the low detail plugin, thank you for such helpful advice! It was in fact the low detail plugin, can't believe I had it toggled.
