### ISSUE TITLE
Models that need plane or color based UVs

### ISSUE THREAD

**Issue by SirFancyBacon** [117HD/RLHD#394]
This is a list of models and their respective locations that need some sort of plane or color identification to fix texturing issues.

If adding to the list please include a screenshot if possible (though not required)
Always add a location, and model ID.

### Objects/Walls ###

- Freminnik Slayer Dungeon inside entrance - 2141
- Trollheim - Edgars Cave Entrance - 3760

### Ground Objects

- Mount Karuulm Lava pools - 34321 & 34322

**Comment by SirFancyBacon** [comment]
2141 - Freminnik Slayer Dungeon
![image](https://github.com/117HD/RLHD/assets/11658143/1e617410-20c8-4507-9bfe-4d8e84fd0dfd)

**Comment by SirFancyBacon** [comment]
Mount Karuulm - 34321 & 34322
![image](https://github.com/117HD/RLHD/assets/11658143/9f7e3e9d-d5f8-4aef-81c8-a5e6e5ded781)

**Comment by SirFancyBacon** [comment]
Trollheim - Edgars Cave Entrance - 3760
![image](https://github.com/117HD/RLHD/assets/11658143/6d699161-5339-4e6b-8081-fd16ec1faf25)

**Comment by Jin-Jiyunsun** [comment]
Karamja - Inside volcano
25069, 25070, 25071, 25072, 25073
![image](https://github.com/117HD/RLHD/assets/37377657/b271f709-081f-4da8-b7ae-a855755a6b72)

**Comment by Jin-Jiyunsun** [comment]
Pipedream but maybe related
![image](https://github.com/117HD/RLHD/assets/37377657/eabf6597-b646-4d3b-833f-342f295c50f7)
![image](https://github.com/117HD/RLHD/assets/37377657/9e447d31-f792-4a05-8875-8eab0a31167a)

**Comment by aHooder** [comment]
This is *hopefully* fixable with https://github.com/117HD/RLHD/commit/e7e784a4f2ca8e1443367b291696bb9abea16e32 :tada:
