### ISSUE TITLE
Moons of Peril Graphical Bugs

### ISSUE THREAD

**Issue by Balanoran** [117HD/RLHD#410]
Noticed some graphical issues in the Moons of Peril dungeon that I wanted to make known. I have provided two screenshots.

The first is the Blue Moon boss room. I am not sure if it is a bug or a design choice for the flames to not have any lighting attached to them. 

The second is outside the Eclipse Moon. Showing a mismatched waterfall, some tiles that do not have the proper texture/appear to not have blended, and also the top right has black squares appear overtop the asset when moving the camera.

![Moons Blue](https://github.com/117HD/RLHD/assets/166740879/8b706edd-23d5-494b-93fe-d51781648653)
![Moons Eclipse Outside](https://github.com/117HD/RLHD/assets/166740879/a4703ec8-6524-4f80-bc08-347100585728)

OS: Windows 11
117 HD Ver: 1.3.3
RuneLite Ver: 1.10.26.4
Launcher Ver: 2.6.4
OSRS Revision: 221

**Comment by Jin-Jiyunsun** [comment]
Will get to work touching this up
