### ISSUE TITLE
Black box visual glitch

### ISSUE THREAD

**Issue by Tiggy24** [117HD/RLHD#508]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/RS117/RLHD/search?type=Issues)

**Describe the bug**
In Lumbridge basement a black rectangle appears near the hole to the caves when viewing at certain angles

**To Reproduce**
1. Go to 'Lumbridge basement'
2. View area near hole to caves
3. if you view from an angle the hole side you will not see it
4. Turning off 117HD plugin the black rectangle disappears
5. At a certain zoom the black rectangle will disappear but moving the view around a few times will bring it back (View this on the Bug disappears screenshot)

**Screenshots**
![Bug appears](https://github.com/user-attachments/assets/8fa189ba-8f08-433b-8669-31cdbc3abe31)
![Bug disppears](https://github.com/user-attachments/assets/00616a24-07c9-49eb-a83d-c519b4e9aed8)
![Bug does not appear](https://github.com/user-attachments/assets/11e8932d-baa0-482b-ae0a-22678a11f5c4)
![Bug sharpest angle](https://github.com/user-attachments/assets/c0aa5e8d-b67c-43c1-81f2-9a7a4b998ad6)

**Expected behavior**
No black rectangle

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: [e.g 1.4.6]

**Additional context**
N/A

**Comment by Mark7625** [comment]
Already been fixed for next update. Thanks for reporting
