### ISSUE TITLE
Lumbridge door entrance needs tiles

### ISSUE THREAD

**Issue by j-meds** [117HD/RLHD#75]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/RS117/RLHD/search?type=Issues)

Lumbridge door entrance may need tiles in front of door

**Screenshots**
![image](https://user-images.githubusercontent.com/12689117/192710196-ad2d7d8c-aaed-4660-9e14-5e32e767f392.png)

**Comment by SirFancyBacon** [comment]
I'll tackle this one; Won't have time to touch it until tomorrow after work most likely; but if i find time tonight i'll get something whipped up!
