### ISSUE TITLE
Ground blending breaks exam centre tiles

### ISSUE THREAD

**Issue by Erveon** [117HD/RLHD#79]
**Describe the bug**
When the Ground Blending option is enabled and you are located in the Exam Centre (south-east of Varrock), the floor tiling produces an unexpected result.

**To Reproduce**
1. Go to the Exam Centre
2. Make sure Ground Blending is enabled in the plugin settings
4. See unexpected result

**Expected behavior**
The tiling to be maintained instead of blended like other textures are

**Screenshots**
With Ground Blending enabled:
![image](https://user-images.githubusercontent.com/13188637/194064109-71677a64-e1af-445b-b198-29fcf6b7f355.png)

With Ground Blending disabled
![image](https://user-images.githubusercontent.com/13188637/194064193-cd2d3c5d-020c-4893-ab5e-3d61e83a6a8c.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.8.34.1
 - Launcher version: 2.1.6

**Comment by SirFancyBacon** [comment]
> Maybe we can work out a way to detect patterns like this and just stop it from blending I noticed it happens in a few places m
That would fix A LOT of areas if it could be done.

Wizards Tower, Rune shop in Port Sarim, Basically half the banks and all kitchens in pre 05 Runescape

**Comment by Mark7625** [comment]
> When 117 made the plugin he manually overrode almost everywhere which has this, including almost all of the stuff that you mentioned @SirFancyBacon. Some were missed, it's hard to catch everything but it works reliably.

I dunoo I've seen this a lot tbh the solution defo works for now but think detecting the tile pattern could be easy enough at some point, but more important things to do

**Comment by SirFancyBacon** [comment]
Yeah, maybe "RLHD 2.0" can have it; but for now i think override is the best option.

What material should these tiles be though? I feel like it would need to be some type of stone/masonry since you don't tile wood (that i've ever seen anyway)

**Comment by Erveon** [comment]
> Yeah, maybe "RLHD 2.0" can have it; but for now i think override is the best option.
> 
> What material should these tiles be though? I feel like it would need to be some type of stone/masonry since you don't tile wood (that i've ever seen anyway)

Looks pretty stone-y to me

**Comment by j-meds** [comment]
> That would fix A LOT of areas if it could be done. Wizards Tower, Rune shop in Port Sarim, Basically half the banks and all kitchens in pre 05 Runescape.

Didn't you fix it at the wizard's tower a while ago ? I went back for a quest there and it has this issue. 


> Something like this i am thinking; But with alternating colors ![image](https://user-images.githubusercontent.com/11658143/194106507-6eb9f7b8-cd80-451d-8e39-0a6d09f54c1b.png)

That looks nice.

**Comment by aHooder** [comment]
If we could just fix specular highlights, we could have nice looking floors like that. It's probably also possible to detect checker patterns in tiles as a scene preprocessing step, then auto disable blending for those.

**Comment by SirFancyBacon** [comment]
> 

Yeah i fixed most of the top but only realized recently i didn't fix the bottom :nerd_face:

**Comment by Mark7625** [comment]
Probs be nice for other patterns that occurs also I think

**Comment by SirFancyBacon** [comment]
I think this is looking pretty good
![image](https://user-images.githubusercontent.com/11658143/194173648-3c2608f8-4c70-498f-afeb-c05d0056c0b3.png)
