### ISSUE TITLE
Ground blending breaks farming guild tiles

### ISSUE THREAD

**Issue by Noctirvia** [117HD/RLHD#86]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/RS117/RLHD/search?type=Issues)

**Describe the bug**
When the Ground Blending option is enabled and you are located in the Farming Guild, the floor tiling produces an unexpected result.

**To Reproduce**
1. Go to the Farming Guild
2. Make sure Ground Blending is enabled in the plugin settings

**Expected behavior**
The tiling to be maintained instead of blank white texture

**Screenshots**
![bug](https://user-images.githubusercontent.com/65740998/195100064-9f6c9ed8-392f-4c59-9a74-9b46a0e6722b.png)
![bug](https://user-images.githubusercontent.com/65740998/195100343-87c37673-02ba-4a27-b8f3-060ae70453ab.png)

**Environment (please complete the following information):**
    OS: Windows 10
    RuneLite version: 1.9.1
    Launcher version: 2.1.0

**Additional context**
[client.log](https://github.com/117HD/RLHD/files/9756116/client.log)

**Comment by aHooder** [comment]
Thanks for reporting this, though this has been fixed already. If you restart RuneLite or update 117HD through the plugin hub panel, this should be back to how it used to be. Here is the commit that fixes it: https://github.com/117HD/RLHD/commit/720957fc92dd0232550a0b539915e7d09bb9e75f
