### ISSUE TITLE
Slow world loading

### ISSUE THREAD

**Issue by Aegarain** [117HD/RLHD#90]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/RS117/RLHD/search?type=Issues)

**Describe the bug**
When the render distance is set above 25, occasionally the world will not load in beyond 25 tiles. When this happens, approaching the unloaded area causes the game to freeze for about 5 seconds. While this also happens when using the gpu plugin, the game doesn't freeze while the world loads.

 My apologies if this is a known bug, something that can't be fixed by a plugin, or something else that makes this bug report unneeded

**To Reproduce**
1. Enable 117 HD in the Plugins Menu
2.  Increase render distance to above 25
3. Run in one direction until the world fails to load
4. Approach unloaded area

**Expected behavior**
The game should load in the world at distances greater than 25 tiles. If this is impossible, the game shouldn't freeze while loading

**Environment (please complete the following information):**
- Windows 10
 - RuneLite version: 1.9.1
 - Launcher version: 2.5.0

**Comment by Mark7625** [comment]
Not much we can do about this current as the base game itself is slow at loading the game world, and HD does extra stuff on top, we can look into making it a bit faster but don't think be a massive change

**Comment by aHooder** [comment]
5 seconds sounds quite slow, but this comes down to your CPU performance. Is it taking this long in a specific area, or does it happen everywhere? Our priority hasn't been on optimizing this, but we could probably take a look to see if there's anything obviously slower than it needs to be.

**Comment by aHooder** [comment]
Scene reloads for me generally take less than 500 ms on an i7 6700K CPU, and typically around 250-350 ms. Is it possible that you're using RuneLite's 32-bit launcher perhaps? You can find a link to RuneLite's website on the OSRS website if you want to download the 64-bit launcher to make sure.

**Comment by Aegarain** [comment]
I was on the 32-bit launcher... Thanks for your help!

**Comment by aHooder** [comment]
Are scene reloads considerably faster now? Like less than 1 second?

**Comment by Aegarain** [comment]
Yep!

**Comment by aHooder** [comment]
Awesome, glad it was as simple as that :+1:

**Comment by Aegarain** [comment]
How are you seeing the exact time for a scene reload?

**Comment by aHooder** [comment]
> How are you seeing the exact time for a scene reload? It's probably nothing, I just want to check the specific speed

Running with `--debug` adds some timers, but not everything. If you want to time it properly, you'll have to make changes to our code. If you need any help with this, please join [our Discord](https://discord.gg/U4p6ChjgSE). I recently spent some time optimizing scene loading though, so this should improve a little bit for the next update. See https://github.com/117HD/RLHD/pull/95 for details.
